name: Windows
on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
       python-version: '3.12'

    - name: Install python dependencies
      run: pip install jinja2
    
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: latest
        cache: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build with CMake
      run: cmake --build ${{github.workspace}}/build --config Debug

    - name: Run tests with CTest
      working-directory: ${{github.workspace}}/build/OloEngine/tests
      run: ctest -V

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: googletest_results_xml
        path: ${{runner.workspace}}/OloEngineBase/test_results/*.xml
        if-no-files-found: 'warn' 